void Infogame(){// Printa todas as regras na tela
	using namespace std;
	cout<< "               Sejam muito bem vindos ao Dominó             \n";
	cout<< "\n           Abaixo estão as regras do nosso game:              \n";
	cout<< "==================================================================\n";
	cout<< "\n1- Cada um dos 4 players terá 7 peças em sua mão, totalizando 28 peças no game.\n";
	cout<< "___________________________\n";
	cout<< "2- A jogada so podera ser feita caso o caractere da peca em maos\n";
	cout<< "Seja igual ao caractere das pecas nas extremidades da mesa.\n";
	cout<< "3-As pecas contem caracteres que sao escolhidos pelos jogadores\n";
	cout<< "4-Antes do jogo comecar as pecas serao embaralhadas e distribuidas aos jogadores\n";
	cout<< "_________________\n";
	cout<< "5-O Jogador que tiver a peca correspondente a peca (1/1 comeca! \n";
	cout<< "_________________\n";
	cout<< "6-O jogador so podera passar a sua vez quando nao\n";
	cout<< "tiver nenhuma peca na mao que possua um caractere igual\n";
	cout<< "aos das extremidades da mesa                      \n";
	cout<< "_________________\n";
	cout<< "7-Em caso de jogo trancar                         \n";
	cout<< "(ninguem conseguir jogar mais nenhuma peca o jogador\n";
	cout<< "com o menor caractere de pecas ganha,em caso de empate\n";
	cout<< "nenhum jogador ganha ponto no placar                 \n";
	cout<< "__________________\n";
	cout<< "8-Nao e permitido o uso de espaco no nome do jogador\n";
	cout<< "__________________\n";
	cout<< "9-Nao e permitido jogadores com nomes iguais      \n";
	cout<< "ou caracteres de pecas iguais \n";
	cout<< "__________________\n";
	cout<< "Grupo: Arthur Sant'Anna; Enzo Gebauer; Luiz Gabriel Guimaraes; Vinicius de Araujo       \n";
	cout<< "          Digite Qualquer coisa para continuar     \n";
	system("pause");
}