void Infogame(){// Printa todas as regras na tela
	using namespace std;
	printf("                 Bem Vindo ao nosso Domino                \n");
	printf("           Seguem as Instrucoes do jogo:              \n");
	printf("==================================================\n");
	printf("1- Todas as pecas disponiveis devem ser utilizadas.  \n");
	printf("Uma vez que o domino possui 28 pecas e 4 players com 7 pecas\n");
	printf("cada um.\n");
	printf("___________________________________________________\n");
	printf("2- A jogada so podera ser feita caso o caractere da peca em maos\n");
	printf("Seja igual ao caractere das pecas nas extremidades da mesa.\n");
	printf("3-As pecas contem caracteres que sao escolhidos pelos jogadores\n");
	printf("4-Antes do jogo comecar as pecas serao embaralhadas e distribuidas aos jogadores\n");
	printf("___________________________________________________\n");
	printf("5-O Jogador que tiver a peca correspondente a peca (1/1) comeca! \n");
	printf("___________________________________________________\n");
	printf("6-O jogador so podera passar a sua vez quando nao\n");
	printf("tiver nenhuma peca na mao que possua um caractere igual\n");
	printf("aos das extremidades da mesa                      \n");
	printf("___________________________________________________\n");
	printf("7-Em caso de jogo trancar                         \n");
	printf("(ninguem conseguir jogar mais nenhuma peca) o jogador\n");
	printf("com o menor caractere de pecas ganha,em caso de empate\n");
	printf("nenhum jogador ganha ponto no placar                 \n");
	printf("____________________________________________________\n");
	printf("8-Nao e permitido o uso de espaco no nome do jogador\n");
	printf("____________________________________________________\n");
	printf("9-Nao e permitido jogadores com nomes iguais      \n");
	printf("ou caracteres de pecas iguais \n");
	printf("____________________________________________________\n");
	printf("          Digite Qualquer coisa para continuar     \n");
	system("pause");
}
