void Infogame(){// Printa todas as regras na tela
	using namespace std;
	cout<< "             Bem Vindo ao nosso Domino                \n";
	cout<< "\n           Seguem as Instrucoes do jogo:              \n";
	cout<< "==================================================\n";
	cout<< "1- Todas as pecas disponiveis devem ser utilizadas.  \n";
	cout<< "   Serao 7 pecas para cada jogador, totalizando 28 pecas.  \n";
	cout<< "_________________________________________________________\n";
	cout<< "2- A jogada so podera ser feita caso o caractere da peca em maos\n";
	cout<< "Seja igual ao caractere das pecas nas extremidades da mesa.\n";
	cout<< "3-As pecas contem caracteres que sao escolhidos pelos jogadores\n";
	cout<< "4-Antes do jogo comecar as pecas serao embaralhadas e distribuidas aos jogadores\n";
	cout<< "___________________________________________________\n";
	cout<< "5-O Jogador que tiver a peca correspondente a peca (1/1 comeca! \n";
	cout<< "___________________________________________________\n";
	cout<< "6-O jogador so podera passar a sua vez quando nao\n";
	cout<< "tiver nenhuma peca na mao que possua um caractere igual\n";
	cout<< "aos das extremidades da mesa                      \n";
	cout<< "___________________________________________________\n";
	cout<< "7-Em caso de jogo trancar                         \n";
	cout<< "(ninguem conseguir jogar mais nenhuma peca o jogador\n";
	cout<< "com o menor caractere de pecas ganha,em caso de empate\n";
	cout<< "nenhum jogador ganha ponto no placar                 \n";
	cout<< "____________________________________________________\n";
	cout<< "8-Nao e permitido o uso de espaco no nome do jogador\n";
	cout<< "____________________________________________________\n";
	cout<< "9-Nao e permitido jogadores com nomes iguais      \n";
	cout<< "ou caracteres de pecas iguais \n";
	cout<< "____________________________________________________\n";
	cout<< "Grupo: Arthur Sant'Anna; Enzo Gebauer; Luiz Gabriel Guimaraes; Vinicius de Araujo       \n";
	cout<< "          Digite Qualquer coisa para continuar     \n";
	system("pause");
}
